# render.yaml

services:
  - name: rails-api-app
    type: web
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rake db:migrate
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rails-api-database
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true

databases:
  - name: rails-api-database
    plan: free
    region: oregon
